const transactions = [
    { date: '2026-06-01', description: 'Food Delivery', category: 'Lifestyle Enjoyment', amount: 335, payment: 'UPI', type: 'Want', notes: 'Outside Food Delivery' },
    { date: '2026-06-02', description: 'Realestate Savings', category: 'Future Me', amount: 90000, payment: 'Bank Transfer', type: 'Saving', notes: 'Used for future land/house buying' },
    { date: '2026-06-02', description: 'Food Delivery', category: 'Lifestyle Enjoyment', amount: 330, payment: 'UPI', type: 'Want', notes: 'Outside Food Delivery' },
    { date: '2026-06-02', description: 'Travel', category: 'Life Infrastructure', amount: 423, payment: 'UPI', type: 'Need', notes: 'Tatkal train ticket for dad from home to hyderabad' },
    { date: '2026-06-02', description: 'Swiggy food', category: 'Lifestyle Enjoyment', amount: 429, payment: 'UPI', type: 'Want', notes: 'Swiggy food / instamart delivery' },
    { date: '2026-06-03', description: 'Mutual Funds SIPs', category: 'Future Me', amount: 23000, payment: 'Bank Transfer', type: 'Saving', notes: 'Mutual Funds SIPs' },
    { date: '2026-06-04', description: 'Uber', category: 'Life Infrastructure', amount: 116, payment: 'UPI', type: 'Need', notes: 'Uber ride to office' },
    { date: '2026-06-05', description: 'Maid salary + some rent', category: 'Rent', amount: 3500, payment: 'UPI', type: 'Need', notes: 'I paid maid salary' },
    { date: '2026-06-05', description: 'Travel', category: 'Life Infrastructure', amount: 423, payment: 'UPI', type: 'Need', notes: 'Tatkal train ticket from hyderabad to home for dad' },
    { date: '2026-06-05', description: 'Botanical garden with dad', category: 'Lifestyle Enjoyment', amount: 100, payment: 'UPI', type: 'Want', notes: 'for a walk in botanical garden with dad' },
    { date: '2026-06-05', description: 'Khazana Jewellery', category: 'Future Me', amount: 90000, payment: 'UPI', type: 'Saving', notes: 'Gold savings' },
    { date: '2026-06-05', description: 'Swiggy food', category: 'Lifestyle Enjoyment', amount: 205, payment: 'UPI', type: 'Want', notes: 'Swiggy food / instamart delivery' },
    { date: '2026-06-06', description: 'Amazon delivery', category: 'Life Infrastructure', amount: 300, payment: 'UPI', type: 'Need', notes: 'amazon delivery' },
    { date: '2026-06-06', description: 'Car insurance', category: 'Life Infrastructure', amount: 10700, payment: 'UPI', type: 'Need', notes: 'Cars insurance' },
    { date: '2026-06-06', description: 'Khazana Jewellery ( previous month )', category: 'Future Me', amount: 9000, payment: 'UPI', type: 'Saving', notes: 'Gold savings' },
    { date: '2026-06-06', description: 'Uber', category: 'Life Infrastructure', amount: 65, payment: 'UPI', type: 'Need', notes: 'Uber travel to railway station' },
    { date: '2026-06-06', description: 'Uber', category: 'Life Infrastructure', amount: 43, payment: 'UPI', type: 'Need', notes: 'I travelled from railway station to home' },
    { date: '2026-06-07', description: 'youtube subscription', category: 'Lifestyle Enjoyment', amount: 90, payment: 'UPI', type: 'Want', notes: 'Youtube Premium subscription' },
    { date: '2026-06-11', description: 'Giveaway of money to relatives', category: 'Donation & Generosity', amount: 300, payment: 'Bank Transfer', type: 'Need', notes: 'Gave money to hari pamala as a generosity' },
    { date: '2026-06-13', description: 'Eating food outside', category: 'Lifestyle Enjoyment', amount: 375, payment: 'UPI', type: 'Want', notes: 'Rameshwaram cafe, eating outside.' },
    { date: '2026-06-13', description: 'Uber', category: 'Life Infrastructure', amount: 120, payment: 'UPI', type: 'Need', notes: 'ride back home from rameshwaram cafe' },
    { date: '2026-06-13', description: 'Roppen T', category: 'Life Infrastructure', amount: 70, payment: 'UPI', type: 'Need', notes: 'No idea where i paid this' },
    { date: '2026-06-14', description: 'Electricity bill ( Staying )', category: 'Rent', amount: 4884, payment: 'UPI', type: 'Need', notes: 'electricity bill i paid.' },
    { date: '2026-06-14', description: 'Uber', category: 'Life Infrastructure', amount: 36, payment: 'UPI', type: 'Need', notes: 'Uber ride to pradyumna place' },
    { date: '2026-06-14', description: 'Eating food outside', category: 'Lifestyle Enjoyment', amount: 380, payment: 'UPI', type: 'Want', notes: 'Ice cream at naturals' },
    { date: '2026-06-15', description: 'SSC fees', category: 'Performance & Growth', amount: 100, payment: 'UPI', type: 'Want', notes: 'SSC tier 1 exam fees' },
    { date: '2026-06-15', description: 'Chit with Ramu maama', category: 'Future Me', amount: 16000, payment: 'UPI', type: 'Saving', notes: 'Ramu maama chit' },
    { date: '2026-06-15', description: 'Rent + all expenses', category: 'Life Infrastructure', amount: 9874, payment: 'UPI', type: 'Need', notes: 'Rent + misc for staying + bills' },
    { date: '2026-06-15', description: 'Food delivery', category: 'Life Infrastructure', amount: 580, payment: 'UPI', type: 'Want', notes: 'Blink it, groceries' },
    { date: '2026-06-17', description: 'Travel', category: 'Life Infrastructure', amount: 1208, payment: 'UPI', type: 'Need', notes: 'Ride back home from hyderabad + bus' },
    { date: '2026-06-17', description: 'RD installment', category: 'Future Me', amount: 5000, payment: 'Bank Transfer', type: 'Saving', notes: 'RD that i save' },
    { date: '2026-06-18', description: 'Petrol for bike', category: 'Donation & Generosity', amount: 110, payment: 'UPI', type: 'Need', notes: 'Pramods bike petrol' },
    { date: '2026-06-18', description: 'Subscriptions ( Netflix )', category: 'Lifestyle Enjoyment', amount: 200, payment: 'UPI', type: 'Want', notes: 'Netflix subscriptions' },
    { date: '2026-06-20', description: 'Uber', category: 'Life Infrastructure', amount: 80, payment: 'UPI', type: 'Need', notes: 'Uber to bus pickup location' },
    { date: '2026-06-20', description: 'Credit card bill ( Jammu trip )', category: 'Lifestyle Enjoyment', amount: 32540, payment: 'Bank Transfer', type: 'Want', notes: 'Jammu trip costs' },
    { date: '2026-06-21', description: 'Travel', category: 'Lifestyle Enjoyment', amount: 2500, payment: 'UPI', type: 'Want', notes: 'Chikballapur trip with family' },
    { date: '2026-06-21', description: 'Fast tag recharge', category: 'Lifestyle Enjoyment', amount: 500, payment: 'UPI', type: 'Want', notes: 'Fast tag recharge' },
    { date: '2026-06-21', description: 'Isha foundation, prasad', category: 'Donation & Generosity', amount: 400, payment: 'UPI', type: 'Want', notes: 'Isha foundation, prasadam' },
    { date: '2026-06-21', description: 'Travel', category: 'Lifestyle Enjoyment', amount: 2000, payment: 'UPI', type: 'Want', notes: 'Petrol filing back home' },
    { date: '2026-06-23', description: 'Black rose for mom', category: 'Life Infrastructure', amount: 24, payment: 'UPI', type: 'Need', notes: 'Black rose for mom' },
    { date: '2026-06-24', description: 'Misc spend', category: 'Donation & Generosity', amount: 150, payment: 'UPI', type: 'Want', notes: 'misc spend' },
    { date: '2026-06-27', description: 'Coorg trip', category: 'Lifestyle Enjoyment', amount: 287, payment: 'UPI', type: 'Want', notes: 'Coorg pramod cough syrup' },
    { date: '2026-06-28', description: 'Coorg trip', category: 'Lifestyle Enjoyment', amount: 150, payment: 'UPI', type: 'Want', notes: 'Snack item ( laddus )' },
    { date: '2026-06-28', description: 'Coorg trip', category: 'Lifestyle Enjoyment', amount: 1400, payment: 'UPI', type: 'Want', notes: 'Buddist temple shopping' },
    { date: '2026-06-28', description: 'Coorg trip', category: 'Lifestyle Enjoyment', amount: 705, payment: 'UPI', type: 'Want', notes: 'snacks shopping.' },
    { date: '2026-06-29', description: 'Coorg trip', category: 'Lifestyle Enjoyment', amount: 280, payment: 'UPI', type: 'Want', notes: 'Cough & Cold balm' },
    { date: '2026-06-29', description: 'Coorg trip', category: 'Lifestyle Enjoyment', amount: 750, payment: 'UPI', type: 'Want', notes: 'Shopping' },
    { date: '2026-06-29', description: 'Go Stops stay', category: 'Lifestyle Enjoyment', amount: 1000, payment: 'UPI', type: 'Want', notes: 'Go stops for me and harshit' },
    { date: '2026-06-29', description: 'Coorg trip', category: 'Lifestyle Enjoyment', amount: 600, payment: 'UPI', type: 'Want', notes: 'Exhibition, games' },
    { date: '2026-06-29', description: 'Coorg trip', category: 'Lifestyle Enjoyment', amount: 700, payment: 'UPI', type: 'Want', notes: 'Eating food outside at filte cafe' },
    { date: '2026-06-30', description: 'Coorg trip', category: 'Lifestyle Enjoyment', amount: 320, payment: 'UPI', type: 'Want', notes: 'breakfast ar ramakrishna cafe' },
    { date: '2026-06-30', description: 'Coorg trip', category: 'Lifestyle Enjoyment', amount: 30, payment: 'UPI', type: 'Want', notes: 'Auto charge from dharmavaram to home' },
    { date: '2026-07-01', description: 'Realestate Savings', category: 'Future Me', amount: 90000, payment: 'Bank Transfer', type: 'Saving', notes: 'Used for future land/house buying' },
    { date: '2026-07-02', description: 'Remote battery cells', category: 'Life Infrastructure', amount: 78, payment: 'UPI', type: 'Need', notes: 'Battery cells for AC remote and thaswi toys' },
    { date: '2026-07-02', description: 'Mutual Funds SIPs', category: 'Future Me', amount: 2000, payment: 'Bank Transfer', type: 'Saving', notes: 'new MFs SIPs' },
    { date: '2026-07-03', description: 'Mutual Funds SIPs', category: 'Future Me', amount: 23000, payment: 'Bank Transfer', type: 'Saving', notes: 'regular MFs SIPs' },
    { date: '2026-07-03', description: 'Donation', category: 'Donation & Generosity', amount: 700, payment: 'UPI', type: 'Need', notes: 'Donation to a child orphanage organisation' },
    { date: '2026-07-03', description: 'Language Learning course', category: 'Donation & Generosity', amount: 670, payment: 'UPI', type: 'Want', notes: 'Telugu learning course for a friend' },
    { date: '2026-07-04', description: 'Petrol for bike', category: 'Life Infrastructure', amount: 600, payment: 'UPI', type: 'Need', notes: 'Petrol for bike' },
    { date: '2026-07-05', description: 'Amazon delivery', category: 'Life Infrastructure', amount: 1524, payment: 'UPI', type: 'Need', notes: 'Mosquito magnet curtain for home - 2 quantity' },
    { date: '2026-07-07', description: 'Subscriptions ( youtube )', category: 'Lifestyle Enjoyment', amount: 90, payment: 'UPI', type: 'Want', notes: 'Youtube Premium subscription' },
    { date: '2026-07-11', description: 'Mis buying for home', category: 'Life Infrastructure', amount: 350, payment: 'UPI', type: 'Need', notes: 'home essentials' },
    { date: '2026-07-13', description: 'Train ticket', category: 'Life Infrastructure', amount: 650, payment: 'UPI', type: 'Need', notes: 'Train ticket ( which i was not able to board)' },
    { date: '2026-07-14', description: 'Hair dye for mom', category: 'Life Infrastructure', amount: 150, payment: 'UPI', type: 'Need', notes: 'Hair dye for mom' },
    { date: '2026-07-15', description: 'Chit with Ramu maama', category: 'Future Me', amount: 16000, payment: 'UPI', type: 'Saving', notes: 'Ramu maama chit' },
    { date: '2026-07-15', description: 'Rent + all expenses', category: 'Rent', amount: 18471, payment: 'UPI', type: 'Need', notes: 'Room rent + other expenses.' },
    { date: '2026-07-15', description: 'Khazana Jewellery', category: 'Future Me', amount: 9000, payment: 'Bank Transfer', type: 'Saving', notes: 'Gold savings' },
    { date: '2026-07-16', description: 'Tirupati Expenses', category: 'Lifestyle Enjoyment', amount: 700, payment: 'UPI', type: 'Want', notes: 'Trip expenses on 16th july' },
    { date: '2026-07-17', description: 'Tirupati Expenses', category: 'Lifestyle Enjoyment', amount: 850, payment: 'UPI', type: 'Want', notes: 'Trip expenses on 17th july' },
    { date: '2026-07-17', description: 'RD installment', category: 'Future Me', amount: 5000, payment: 'Bank Transfer', type: 'Saving', notes: 'RD that i save' },
    { date: '2026-07-18', description: 'Subscriptions (Netflix)', category: 'Lifestyle Enjoyment', amount: 200, payment: 'UPI', type: 'Want', notes: 'Netflix subscriptions' },
    { date: '2026-07-19', description: 'BSNL Wifi', category: 'Life Infrastructure', amount: 710, payment: 'Bank Transfer', type: 'Need', notes: 'Wifi' },
    { date: '2026-07-19', description: 'Bus Booking from home to hyd', category: 'Life Infrastructure', amount: 1350, payment: 'Credit Card', type: 'Need', notes: 'Travel back to hyderabad from home' },
    { date: '2026-07-20', description: 'Domain Bought for classyainews.com', category: 'Performance & Growth', amount: 3000, payment: 'Credit Card', type: 'Want', notes: 'classyainews.com domain was bought in square spaces' },
    { date: '2026-07-21', description: 'Auto from bus stop to westend apartments', category: 'Life Infrastructure', amount: 90, payment: 'UPI', type: 'Need', notes: 'cab' },
    { date: '2026-07-22', description: 'HDFC Credit Card payment', category: 'Lifestyle Enjoyment', amount: 1300, payment: 'UPI', type: 'Need', notes: 'Credit card bill' },
    { date: '2026-07-24', description: 'Amazon delivery ( shorts 2 + floor cleaner )', category: 'Life Infrastructure', amount: 1000, payment: 'Credit Card', type: 'Need', notes: 'Clothes and floor cleaner' },
    { date: '2026-07-25', description: 'Petrol for bike', category: 'Life Infrastructure', amount: 180, payment: 'UPI', type: 'Want', notes: 'Petrol for bike' },
    { date: '2026-07-26', description: 'Medicine for ortho', category: 'Performance & Growth', amount: 600, payment: 'UPI', type: 'Need', notes: 'Medicines' },
    { date: '2026-08-01', description: 'Realestate Savings', category: 'Future Me', amount: 90000, payment: 'UPI', type: 'Saving', notes: 'Used for future land/house buying' },
    { date: '2026-08-01', description: 'dinner ( idli + dosa )', category: 'Lifestyle Enjoyment', amount: 100, payment: 'UPI', type: 'Need', notes: 'Dinner food' },
    { date: '2026-08-01', description: 'Spine care ( QI clinic )', category: 'Performance & Growth', amount: 1400, payment: 'UPI', type: 'Need', notes: 'Suppliments for back pain' },
    { date: '2026-08-01', description: 'Botanical garden with pradyumna', category: 'Lifestyle Enjoyment', amount: 170, payment: 'UPI', type: 'Need', notes: 'walk with pradyumna in botanical.' },
    { date: '2026-08-03', description: 'Mutual Funds SIPs', category: 'Future Me', amount: 30000, payment: 'Bank Transfer', type: 'Saving', notes: 'Mutual Funds SIPs' },
    { date: '2026-08-05', description: 'Money transfer to amazon pay wallet', category: 'Life Infrastructure', amount: 500, payment: 'UPI', type: 'Need', notes: 'Money transfer to wallet' },
    { date: '2026-08-05', description: 'IRCTC Tikcets', category: 'Life Infrastructure', amount: 820, payment: 'UPI', type: 'Need', notes: 'Mom and dad travel to hyderabad from home' },
    { date: '2026-08-05', description: 'Train IRCTC Tickets', category: 'Life Infrastructure', amount: 1600, payment: 'UPI', type: 'Need', notes: 'Mom and dad travel to home from hyderabad' },
    { date: '2026-08-06', description: 'Electricity bill ( Staying )', category: 'Rent', amount: 744, payment: 'UPI', type: 'Need', notes: 'electricity bill i paid.' },
    { date: '2026-08-06', description: 'Chai with Faizaan', category: 'Lifestyle Enjoyment', amount: 50, payment: 'UPI', type: 'Want', notes: 'Chai with faizaan' },
    { date: '2026-08-07', description: 'youtube subscription', category: 'Lifestyle Enjoyment', amount: 90, payment: 'UPI', type: 'Want', notes: 'Youtube Premium subscription' },
    { date: '2026-08-08', description: 'Petrol for bike', category: 'Life Infrastructure', amount: 200, payment: 'UPI', type: 'Need', notes: 'petrol for bike' },
    { date: '2026-08-09', description: 'Medicine for mom ( incumin tablets )', category: 'Life Infrastructure', amount: 2500, payment: 'UPI', type: 'Need', notes: 'Incumin tablets' },
    { date: '2026-08-09', description: 'Bought amazon pay coupon', category: 'Life Infrastructure', amount: 30, payment: 'UPI', type: 'Need', notes: 'Magic pin coupon bought' },
    { date: '2026-08-12', description: 'Paid for friend', category: 'Donation & Generosity', amount: 22, payment: 'UPI', type: 'Need', notes: 'Gave money to faizaan to buy' },
    { date: '2026-08-15', description: 'Rent + all expenses', category: 'Rent', amount: 16003, payment: 'UPI', type: 'Need', notes: 'Rent + misc for staying + bills' },
    { date: '2026-08-15', description: 'Splitwise amount to pradyumna', category: 'Lifestyle Enjoyment', amount: 350, payment: 'UPI', type: 'Want', notes: 'Food + eating outside' },
    { date: '2026-08-15', description: 'Eating out with pradyumna', category: 'Lifestyle Enjoyment', amount: 380, payment: 'UPI', type: 'Want', notes: 'Taaza kitchen morning breakfast' },
    { date: '2026-08-15', description: 'Chit with Ramu maama', category: 'Future Me', amount: 16000, payment: 'UPI', type: 'Saving', notes: 'Ramu maama chit' },
    { date: '2026-08-15', description: 'Sweet corn bought', category: 'Lifestyle Enjoyment', amount: 20, payment: 'UPI', type: 'Need', notes: 'Sweet corn bought' },
    { date: '2026-08-15', description: 'Mom and dad cab pickup', category: 'Performance & Growth', amount: 100, payment: 'UPI', type: 'Want', notes: 'Cab pickup' },
    { date: '2026-08-16', description: 'Petrol for bike', category: 'Lifestyle Enjoyment', amount: 200, payment: 'Credit Card', type: 'Want', notes: 'Petrol for bike' },
    { date: '2026-08-17', description: 'Khazana Jewellery', category: 'Future Me', amount: 9000, payment: 'UPI', type: 'Saving', notes: 'Gold savings' },
    { date: '2026-08-17', description: 'Cab from home to office', category: 'Lifestyle Enjoyment', amount: 156, payment: 'UPI', type: 'Need', notes: 'Took mom and dad to office in cab' },
    { date: '2026-08-17', description: 'Cab to shilpa ramam', category: 'Lifestyle Enjoyment', amount: 72, payment: 'UPI', type: 'Need', notes: 'Cab to shilpa ramam with parents' },
    { date: '2026-08-17', description: 'Cab from shilpa ramam to flat', category: 'Lifestyle Enjoyment', amount: 100, payment: 'UPI', type: 'Need', notes: 'Cab to flat with parents' },
    { date: '2026-08-17', description: 'Cab to railway station', category: 'Lifestyle Enjoyment', amount: 180, payment: 'UPI', type: 'Need', notes: 'Cab to drop off parents at railway station.' },
    { date: '2026-08-17', description: 'Curd + ticket to kacheguda + bike drop off', category: 'Lifestyle Enjoyment', amount: 120, payment: 'UPI', type: 'Need', notes: 'My expense after dropping parents and coming back to flat' },
    { date: '2026-08-17', description: 'RD installment', category: 'Future Me', amount: 5000, payment: 'Bank Transfer', type: 'Saving', notes: 'RD that i save' },
    { date: '2026-08-17', description: 'Netflix subscription', category: 'Lifestyle Enjoyment', amount: 200, payment: 'UPI', type: 'Want', notes: 'Netflix subscriptions' },
    { date: '2026-08-19', description: 'Wifi bill paid', category: 'Life Infrastructure', amount: 720, payment: 'UPI', type: 'Need', notes: 'Wifi bill' },
    { date: '2026-08-20', description: 'Food eatout ( idli + bonda)', category: 'Lifestyle Enjoyment', amount: 100, payment: 'UPI', type: 'Want', notes: 'Food eating outside' },
    { date: '2026-08-20', description: 'Wint wealth bond investment', category: 'Future Me', amount: 148826, payment: 'Bank Transfer', type: 'Saving', notes: 'Wint wealth ( Govt Bond + Private Bond )' },
    { date: '2026-08-21', description: 'Cricket amount with google colleagues', category: 'Performance & Growth', amount: 200, payment: 'UPI', type: 'Want', notes: 'Played box cricket with colleagues' },
    { date: '2026-08-22', description: 'Urban clap for machine repair', category: 'Rent', amount: 300, payment: 'UPI', type: 'Need', notes: 'Washing machine repair' },
    { date: '2026-08-22', description: 'Credit card bill HDFC', category: 'Life Infrastructure', amount: 9835, payment: 'UPI', type: 'Need', notes: 'Credit card bill for hdfc' },
    { date: '2026-08-23', description: 'Curd packets + tomatoes', category: 'Life Infrastructure', amount: 50, payment: 'Credit Card', type: 'Need', notes: 'Veggies + curd' },
    { date: '2026-08-24', description: 'Petrol for bike', category: 'Lifestyle Enjoyment', amount: 200, payment: 'Credit Card', type: 'Need', notes: 'Petrol for bike to and fro from office' },
    { date: '2026-08-26', description: 'Niloufer cafe', category: 'Lifestyle Enjoyment', amount: 180, payment: 'Credit Card', type: 'Want', notes: 'Chai with arihant' },
    { date: '2026-08-28', description: 'Realestate Savings', category: 'Future Me', amount: 90000, payment: 'Bank Transfer', type: 'Saving', notes: 'Used for future land/house buying' },
    { date: '2026-08-28', description: 'Gift to Guna on rakhi', category: 'Donation & Generosity', amount: 3000, payment: 'UPI', type: 'Need', notes: 'Gift to guna on raakhi' },
    { date: '2026-08-29', description: 'LIC insurance premium for me', category: 'Future Me', amount: 13340, payment: 'UPI', type: 'Saving', notes: 'LIC health insurance' },
    { date: '2026-08-30', description: 'Food ( paranthawaala )', category: 'Life Infrastructure', amount: 203, payment: 'Credit Card', type: 'Want', notes: 'Food ( 2 paranthas )' },
    { date: '2026-08-31', description: 'Petrol for bike', category: 'Lifestyle Enjoyment', amount: 220, payment: 'Credit Card', type: 'Want', notes: 'Petrol for bike' },
    { date: '2026-09-03', description: 'Petrol for bike', category: 'Lifestyle Enjoyment', amount: 220, payment: 'Credit Card', type: 'Want', notes: 'Petrol for bike' },
    { date: '2026-09-04', description: 'Corn bought to eat', category: 'Life Infrastructure', amount: 25, payment: 'UPI', type: 'Need', notes: 'Corn brought to eat' },
    { date: '2026-09-05', description: 'Phone recharge for year', category: 'Life Infrastructure', amount: 3600, payment: 'UPI', type: 'Need', notes: 'Phone recharge for me' },
    { date: '2026-09-05', description: 'Chai with Faizaan', category: 'Lifestyle Enjoyment', amount: 50, payment: 'Credit Card', type: 'Want', notes: 'Chai' },
    { date: '2026-09-05', description: 'Food Outside ( dinner )', category: 'Lifestyle Enjoyment', amount: 90, payment: 'Credit Card', type: 'Want', notes: 'Food ( dinner + tirumala tiffins )' },
    { date: '2026-09-06', description: 'Breakfast food order', category: 'Lifestyle Enjoyment', amount: 150, payment: 'UPI', type: 'Want', notes: 'Food delivery' },
    { date: '2026-09-06', description: 'Bus ticket from hyderabad to bathalapalli', category: 'Life Infrastructure', amount: 650, payment: 'Credit Card', type: 'Need', notes: '( used along with so many coins + travelling to home)' },
    { date: '2026-07-21', description: 'cab from bus stop to flat', category: 'Life Infrastructure', amount: 90, payment: 'UPI', type: 'Need', notes: 'Bike rapido fro me to come to flat' },
    { date: '2026-08-01', description: 'Protein Powder', category: 'Performance & Growth', amount: 3714, payment: 'Credit Card', type: 'Want', notes: 'Muscle Blaze protein powder' },
    { date: '2026-07-17', description: 'Shilparamam entry tickets and boating', category: 'Lifestyle Enjoyment', amount: 270, payment: 'Credit Card', type: 'Want', notes: 'Fun time with parents in shilparamam' },
    { date: '2026-07-24', description: 'Amazon ( Tricycle for thaswika )', category: 'Donation & Generosity', amount: 2704, payment: 'Credit Card', type: 'Want', notes: 'Gift to Thaswi for riding tricycle' },
    { date: '2026-08-05', description: 'Chair for mom', category: 'Donation & Generosity', amount: 1450, payment: 'Credit Card', type: 'Need', notes: 'Special chair for mom' },
    { date: '2026-08-05', description: 'Rosemary hair oil', category: 'Performance & Growth', amount: 500, payment: 'Credit Card', type: 'Need', notes: 'Hair oil' }
];

const categoryColors = {
    'Lifestyle Enjoyment': '#FFB020',
    'Life Infrastructure': '#4AB8FF',
    'Future Me': '#00D4AA',
    'Donation & Generosity': '#9B51E0',
    'Rent': '#FF5C7A',
    'Performance & Growth': '#8B84FF'
};

const categoryIcons = {
    'Lifestyle Enjoyment': '🍔',
    'Life Infrastructure': '🏠',
    'Future Me': '💎',
    'Donation & Generosity': '💝',
    'Rent': '🏠',
    'Performance & Growth': '📚'
};